name: Path Generator

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs: 
    call-path-generator:
        uses: ./.github/workflows/path-generator.yml

    code-validation:
      runs-on: ubuntu-latest
      needs: call-path-generator
      steps:
        - run: echo ${{ needs.call-path-generator.outputs.generated_path }}