name: Caller

on:
  workflow_dispatch:
    inputs:
      deployment-mode:
        description: 'Deployment Mode:'
        default: 'Deploy only'
        type: choice
        options:
          - Deploy only
          - Deploy and Publish Portals
          - Publish Portals only
      create-tag:
        type: boolean
        default: true
        description: 'Create Git tag - only after successful deployment'


jobs: 

  # passing the secret to a nested reusable workflow
  pass-secret-to-workflow:
    uses: ./.github/workflows/called.yml
    secrets:
        target-username: ${{ secrets.TEST_SECRET1 }}
        target-consumer-key: ${{ secrets.TEST_SECRET2 }}