# This pipeline deploys SF code in ST (smoke-testing) org on scheule and creates git tag after successful deployment

name: 'Code Deploy - ST'

on:
  workflow_dispatch:

jobs:
  version-bump-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git Semantic Version
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.3
        with:
              # The prefix to use to identify tags
          tag_prefix: "v"
              # A string which, if present in a git commit, indicates that a change represents a
              # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
              # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
          minor_pattern: "(MINOR)"
              # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      - name: echo-runs
        run: |
          echo ${{ steps.versioning.outputs.version }}
          echo ${{ steps.versioning.outputs.version_tag }}
      -name: get-latest-tag
        run: |
          git config --global user.email "6andrey@gmail.com"
          git config --global user.name "Andrey Shestakov"
          git tag --list ${{ steps.versioning.outputs.version_tag }}

  deploy-n-tag:
    if: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install-sfdx
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install
      - name: connect-to-st-org
        run: |
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a st_org
      - name: deploy-to-st-org
        run: sfdx force:source:deploy -p src/core-crm -w 30 -u st_org
      - name: create-tag
        run: |
          git config --global user.email "6andrey@gmail.com"
          git config --global user.name "Andrey Shestakov"
          git tag -a ${{ steps.versioning.outputs.version_tag }} -m "test annotation"
          git push origin --tags

          # https://stackoverflow.com/questions/17790123/shell-check-if-a-git-tag-exists-in-an-if-else-statement
          # git log v0.0.1...v0.0.2 --merges 
          # git log v0.0.1...v0.0.2 --pretty=format:"%s | %an | %ae" --merges

          # Events that trigger workflow
          # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call