name: Path Generator

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-path-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run git diff for "core-crm" folder
        id: step-git-diff-core-crm
        run: |
          echo "git diff --name-only:"
          echo $(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)
          echo "*********************"
          echo "git diff --exit-code:"
          echo $(git diff --exit-code origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)
          echo "*********************"
          if [ $"(git diff --quiet origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)" != 0 ]
          then
            echo "src-core folder changed"
          else
            echo "src-core folder NOT changed"
          fi
            
      - name: Run git diff for "sales" folder
        id: step-git-diff-sales
        run: |
          echo "git diff --name-only:"
          echo $(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/sales)
          echo "*********************"
          if [ $"(git diff --quiet origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/sales)" != 0 ]
          then
            echo "sales folder changed"
          else
            echo "sales folder NOT changed"
          fi
