name: Path Generator

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-path-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run git diff for "core-crm" folder
        id: step-git-diff-core-crm
        run: |
          echo "git diff --name-only:"
          echo $(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)
          echo "*********************"
          if [ $"(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)" = '' ]
          then
            echo "src-core folder NOT changed"
            echo "core-crm-folder=" >> $GITHUB_OUTPUT
          else
            echo "src-core folder changed"
            echo "core-crm-folder=src/core-crm" >> $GITHUB_OUTPUT
          fi

      - name: Get core-crm folder
        run: |
          echo "*********************"
          echo "Output:"
          echo ${{ steps.step-git-diff-core-crm.outputs.core-crm-folder }}
          echo "*********************"
            
      - name: Run git diff for "sales" folder
        id: step-git-diff-sales
        run: |
          echo "git diff --name-only:"
          echo $(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/sales)
          echo "*********************"
          if [ -z $"(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/sales)" ]
          then
            echo "sales folder NOT changed"
          else
            echo "sales folder changed"
          fi
