name: Path Generator

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-path-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run git diff for "scr-core" folder
        id: step-git-diff-core-crm
        run: |
          echo $(git diff --quiet origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)
          if [ $(git diff --quiet origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm) -eq "1" ]
          then
            echo "src-core folder changed"
          else
            echo "src-core folder NOT changed"
          fi
            
      - name: Run git diff for "sales" folder
        id: step-git-diff-sales
        run: git diff --quiet origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/sales || echo sales folder changed
