name: Path Generator

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-path-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run git diff for "scr-core" folder
        id: step-git-diff-core-crm
        run: git diff --quiet ${{ github.base_ref }} ${{ github.head_ref }} -- src/core-crm || echo src-core folder changed

      - name: Run git diff for "sales" folder
        id: step-git-diff-sales
        run: git diff --quiet ${{ github.base_ref }} ${{ github.head_ref }} -- src/sales || echo sales folder changed
