name: Path Generator

on:
  workflow_call:

jobs:
  create-path-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run git diff for "core-crm" folder
        id: step-git-diff-core-crm
        run: |
          echo "git diff --name-only:"
          diff_output=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/core-crm)
          echo $diff_output
          echo "*********************"
          if [ -z $diff_output ]
          then
            echo "src-core folder NOT changed"
            echo "core-crm-folder=" >> $GITHUB_OUTPUT
          else
            echo "src-core folder changed"
            echo "core-crm-folder=src/core-crm" >> $GITHUB_OUTPUT
          fi
            
      - name: Run git diff for "sales" folder
        id: step-git-diff-sales
        run: |
          echo "git diff --name-only:"
          diff_output=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/sales)
          echo $diff_output
          echo "*********************"
          if [ -z $diff_output ]
          then
            echo "sales folder NOT changed"
            echo "sales-folder=" >> $GITHUB_OUTPUT
          else
            echo "sales folder changed"
            echo "sales-folder=src/sales" >> $GITHUB_OUTPUT
          fi

      - name: Concatenation
        run: |
          echo "*********************"
          echo "Output core-crm folder:"
          core_crm=${{ steps.step-git-diff-core-crm.outputs.core-crm-folder }}
          echo $core_crm
          echo "*********************"
          echo "Output sales folder:"
          sales=${{ steps.step-git-diff-sales.outputs.sales-folder }}
          echo $sales
          echo "*********************"
          echo "all paths:"
          paths=($core_crm $sales)
          echo "${paths[0]}"
          echo "${paths[1]}"
          echo "${paths[@]}"
          non_empty_paths=()

          for str in "${paths[@]}"; do
            if [[ -n "$str" ]]; then
              non_empty_paths+=("$str")
            fi
          done

          concatenated_path=$(IFS=,; echo "${non_empty_paths[*]}")
          echo "*********************"
          echo "concatenated_path:"
          echo $concatenated_path